<table class="stec-layout-week" cellspacing="0" cellpadding="0">
    <tbody>
        <tr class="stec-layout-week-daylabel">
            <td>
                <p>-</p> <!-- day label -->
                <p>-</p> <!-- day label short -->
                <p>-</p> <!-- day label very short -->
            </td>
            <td>
                <p>-</p>
                <p>-</p>
                <p>-</p>
            </td>
            <td>
                <p>-</p>
                <p>-</p>
                <p>-</p>
            </td>
            <td>
                <p>-</p>
                <p>-</p>
                <p>-</p>
            </td>
            <td>
                <p>-</p>
                <p>-</p>
                <p>-</p>
            </td>
            <td>
                <p>-</p>
                <p>-</p>
                <p>-</p>
            </td>
            <td>
                <p>-</p>
                <p>-</p>
                <p>-</p>
            </td>
        </tr>

        <tr class="stec-layout-week-weekrow stec-layout-week-weekrow-last">
            <?php for ($cell = 0; $cell < 7; $cell++) : ?>
                <td class="stec-layout-week-daycell">
                    <div class="stec-layout-week-daycell-wrap">
                        <p class="stec-layout-week-daycell-num">DN_T</p>
                        <ul class="stec-layout-week-daycell-events">
                            
                        </ul>
                    </div>
                </td>
            <?php endfor; ?>
        </tr>

        <tr class="stec-layout-week-eventholder stec-event-holder">
            <td colspan="7">
                <ul class="stec-layout-events">
                    <?php
                    // Generated by JS
                    // include("layout.event.inc.php");
                    ?>
                </ul>
            </td>
        </tr>
    </tbody>
</table>