<?php

namespace Stachethemes\Stec;
?>


<div class="stec-layout-day">

    <div class="stec-layout-day-eventholder stec-event-holder">
        <ul class="stec-layout-events">
            <?php
            // Generated by JS
            // include("layout.event.inc.php");
            ?>
        </ul>
    </div>

    <p class="stec-layout-day-noevents"><?php _e("You have no events for this day", 'stec'); ?></p>
</div>